/// Flutter icons CustomIcons2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons2
///      fonts:
///       - asset: fonts/CustomIcons2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons2 {
  CustomIcons2._();

  static const _kFontFam = 'CustomIcons2';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_small = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_small = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invoice = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
